use std::sync::Arc;

use solana_pubkey::Pubkey;
use solana_rpc_client_api::config::{RpcAccountInfoConfig, RpcProgramAccountsConfig};
use tokio::sync::mpsc::Sender;
use url::Url;

use crate::types::{RequestId, SerdePubkey, SubscriberId};

use super::notification::PubsubMessage;

/// Possible subscription actions
#[derive(Clone, Debug)]
pub enum SubscriptionAction {
    Subscribe(Subscription),
    Unsubscribe(Unsubscription),
}

#[derive(Clone, Debug)]
pub struct Subscription {
    /// Unique ID of request generated by internal actor
    pub request_id: RequestId,
    /// Unique ID of the actor, which generated the request
    pub subscriber_id: SubscriberId,
    /// Arbitrary json encoded request websocket
    pub payload: json::Value,
    /// Channel endpoint to communicate udpates back to actor
    pub tx: Sender<PubsubMessage>,
    /// URL of the upstream where to forward the subscription request
    pub destination: Arc<Url>,
}

impl Subscription {
    pub fn clone_with_destination(&self, url: Arc<Url>) -> Self {
        let mut clone = self.clone();
        clone.destination = url;
        clone
    }

    pub fn to_unsubsciption(&self, method: &'static str) -> SubscriptionAction {
        SubscriptionAction::Unsubscribe(Unsubscription {
            subscriber_id: self.subscriber_id,
            request_id: self.request_id,
            destination: self.destination.clone(),
            method,
        })
    }
}

#[derive(Clone, Debug)]
pub struct Unsubscription {
    /// Unique ID of the actor, which generated the request
    pub subscriber_id: SubscriberId,
    /// ID of request, which was used for corresponding subscription request
    pub request_id: RequestId,
    /// name of unsubscription request (e.g. accountUnsubscribe)
    pub method: &'static str,
    /// URL of the upstream where to forward the unsubscription request
    pub destination: Arc<Url>,
}

impl SubscriptionAction {
    pub fn destination(&self) -> &Url {
        match self {
            Self::Subscribe(s) => &s.destination,
            Self::Unsubscribe(u) => &u.destination,
        }
    }
}

#[inline(always)]
pub fn account_subscription_json(
    id: RequestId,
    pubkey: Pubkey,
    params: Option<RpcAccountInfoConfig>,
) -> json::Value {
    json::json!({
        "jsonrpc": "2.0",
        "id": id,
        "method": "accountSubscribe",
        "params": [
            SerdePubkey(pubkey),
            params
        ]
    })
}

#[inline(always)]
pub fn program_subscription_json(
    id: RequestId,
    pubkey: Pubkey,
    params: Option<RpcProgramAccountsConfig>,
) -> json::Value {
    json::json!({
        "jsonrpc": "2.0",
        "id": id,
        "method": "programSubscribe",
        "params": [
            SerdePubkey(pubkey),
            params
        ]
    })
}
