name: Magic Router Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  rust-checks:
    runs-on: ubuntu-latest
    container:
      image: rust:alpine

    steps:
    - uses: actions/checkout@v4
    - name: Run rustfmt
      run: cargo fmt --check
    - name: Run clippy
      run: cargo clippy -- -D warnings

  test-and-build:
    runs-on: ubuntu-latest
    container:
      image: rust:latest

    needs: rust-checks

    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      run: cargo test 
    - name: Build release
      run: cargo build --release

